
// This file has been generated by the GUI designer. Do not modify.
namespace DeSERt
{
	public partial class BrightnessPreview
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image PreviewImage;
		private global::Gtk.HScale PrevImgSlide;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeSERt.BrightnessPreview
			this.WidthRequest = 630;
			this.HeightRequest = 470;
			this.Name = "DeSERt.BrightnessPreview";
			this.Title = global::Mono.Unix.Catalog.GetString ("BrightnessPreview");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("DeSERt.DeSERt-Icon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.DestroyWithParent = true;
			// Container child DeSERt.BrightnessPreview.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.PreviewImage = new global::Gtk.Image ();
			this.PreviewImage.WidthRequest = 600;
			this.PreviewImage.HeightRequest = 400;
			this.PreviewImage.Name = "PreviewImage";
			this.fixed2.Add (this.PreviewImage);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.PreviewImage]));
			w1.X = 15;
			w1.Y = 15;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.PrevImgSlide = new global::Gtk.HScale (null);
			this.PrevImgSlide.WidthRequest = 600;
			this.PrevImgSlide.CanFocus = true;
			this.PrevImgSlide.Name = "PrevImgSlide";
			this.PrevImgSlide.Adjustment.Lower = 1D;
			this.PrevImgSlide.Adjustment.Upper = 100D;
			this.PrevImgSlide.Adjustment.PageIncrement = 10D;
			this.PrevImgSlide.Adjustment.StepIncrement = 1D;
			this.PrevImgSlide.Adjustment.Value = 1D;
			this.PrevImgSlide.DrawValue = true;
			this.PrevImgSlide.Digits = 0;
			this.PrevImgSlide.ValuePos = ((global::Gtk.PositionType)(2));
			this.fixed2.Add (this.PrevImgSlide);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.PrevImgSlide]));
			w2.X = 10;
			w2.Y = 420;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 644;
			this.DefaultHeight = 507;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.PrevImgSlide.ValueChanged += new global::System.EventHandler (this.OnPrevImgSlideValueChanged);
		}
	}
}
