
// This file has been generated by the GUI designer. Do not modify.
namespace DeSERt
{
	public partial class CreateFilterset
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Label label2;
		private global::Gtk.FileChooserButton RefImgChooser;
		private global::Gtk.Label label3;
		private global::Gtk.FileChooserButton FilterImgChooser;
		private global::Gtk.Button CancelButton;
		private global::Gtk.Button SaveButton;
		private global::Gtk.Label label4;
		private global::Gtk.Entry FiltersetnameEntry;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView ValueTable;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeSERt.CreateFilterset
			this.WidthRequest = 570;
			this.HeightRequest = 380;
			this.Name = "DeSERt.CreateFilterset";
			this.Title = global::Mono.Unix.Catalog.GetString ("Create Filterset");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 570;
			this.DefaultHeight = 380;
			this.DestroyWithParent = true;
			// Container child DeSERt.CreateFilterset.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Add Reference Image:");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w1.X = 15;
			w1.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.RefImgChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
			this.RefImgChooser.WidthRequest = 120;
			this.RefImgChooser.Name = "RefImgChooser";
			this.fixed1.Add (this.RefImgChooser);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.RefImgChooser]));
			w2.X = 35;
			w2.Y = 80;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Add Filter Image:");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w3.X = 15;
			w3.Y = 120;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.FilterImgChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
			this.FilterImgChooser.WidthRequest = 120;
			this.FilterImgChooser.Name = "FilterImgChooser";
			this.fixed1.Add (this.FilterImgChooser);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.FilterImgChooser]));
			w4.X = 35;
			w4.Y = 140;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.WidthRequest = 80;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.fixed1.Add (this.CancelButton);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CancelButton]));
			w5.X = 370;
			w5.Y = 310;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.SaveButton = new global::Gtk.Button ();
			this.SaveButton.WidthRequest = 80;
			this.SaveButton.CanFocus = true;
			this.SaveButton.Name = "SaveButton";
			this.SaveButton.UseStock = true;
			this.SaveButton.UseUnderline = true;
			this.SaveButton.Label = "gtk-save";
			this.fixed1.Add (this.SaveButton);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SaveButton]));
			w6.X = 460;
			w6.Y = 310;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Filterset Name:");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w7.X = 20;
			w7.Y = 15;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.FiltersetnameEntry = new global::Gtk.Entry ();
			this.FiltersetnameEntry.CanFocus = true;
			this.FiltersetnameEntry.Name = "FiltersetnameEntry";
			this.FiltersetnameEntry.Text = global::Mono.Unix.Catalog.GetString ("Unnamed Filterset");
			this.FiltersetnameEntry.IsEditable = true;
			this.FiltersetnameEntry.InvisibleChar = '?';
			this.fixed1.Add (this.FiltersetnameEntry);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.FiltersetnameEntry]));
			w8.X = 120;
			w8.Y = 10;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ValueTable = new global::Gtk.NodeView ();
			this.ValueTable.WidthRequest = 350;
			this.ValueTable.HeightRequest = 230;
			this.ValueTable.CanFocus = true;
			this.ValueTable.Name = "ValueTable";
			this.ValueTable.EnableSearch = false;
			this.GtkScrolledWindow.Add (this.ValueTable);
			this.fixed1.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
			w10.X = 170;
			w10.Y = 45;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.Hidden += new global::System.EventHandler (this.OnHidden);
			this.RefImgChooser.SelectionChanged += new global::System.EventHandler (this.OnRefImgChooserSelectionChanged);
			this.FilterImgChooser.SelectionChanged += new global::System.EventHandler (this.OnFilterImgChooserSelectionChanged);
			this.CancelButton.Clicked += new global::System.EventHandler (this.OnCancelButtonClicked);
			this.SaveButton.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
			this.ValueTable.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnValueTableKeyPressEvent);
		}
	}
}
