
// This file has been generated by the GUI designer. Do not modify.
namespace DeSERt
{
	public partial class Help
	{
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView Helpnode;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView Helptext;
		private global::Gtk.Button buttonOK;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeSERt.Help
			this.Name = "DeSERt.Help";
			this.Title = global::Mono.Unix.Catalog.GetString ("Help");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-help", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child DeSERt.Help.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "HelpBox";
			w1.BorderWidth = ((uint)(2));
			// Container child HelpBox.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 166;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.WidthRequest = 100;
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.Helpnode = new global::Gtk.NodeView ();
			this.Helpnode.WidthRequest = 100;
			this.Helpnode.CanFocus = true;
			this.Helpnode.Name = "Helpnode";
			this.GtkScrolledWindow.Add (this.Helpnode);
			this.alignment2.Add (this.GtkScrolledWindow);
			this.hpaned1.Add (this.alignment2);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.alignment2]));
			w4.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.WidthRequest = 300;
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.Helptext = new global::Gtk.TextView ();
			this.Helptext.WidthRequest = 300;
			this.Helptext.CanFocus = true;
			this.Helptext.Name = "Helptext";
			this.Helptext.Editable = false;
			this.GtkScrolledWindow1.Add (this.Helptext);
			this.alignment1.Add (this.GtkScrolledWindow1);
			this.hpaned1.Add (this.alignment1);
			w1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.hpaned1]));
			w8.Position = 0;
			// Internal child DeSERt.Help.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "ButtonActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child ButtonActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOK = new global::Gtk.Button ();
			this.buttonOK.CanDefault = true;
			this.buttonOK.CanFocus = true;
			this.buttonOK.Name = "buttonOK";
			this.buttonOK.UseStock = true;
			this.buttonOK.UseUnderline = true;
			this.buttonOK.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOK, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonOK]));
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 773;
			this.DefaultHeight = 472;
			this.Show ();
			this.Helpnode.CursorChanged += new global::System.EventHandler (this.OnHelpnodeCursorChanged);
			this.buttonOK.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
		}
	}
}
